workflows: macos hell

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -44,17 +44,10 @@ jobs:
       run: |
         set +e
         uname -a
-        { compgen -c clang; compgen -c gcc; } | grep -E '^(clang|gcc)(-[1-9][0-9]*(\.[0-9]+)*)?$' | sort -V -u -r > compilers
-        grep -Fxe clang -e gcc compilers > default-compilers
-        cat default-compilers | xargs -I§ bash -c 'realpath "$(command -v §)" 2>/dev/null' | paste - default-compilers | grep -Ev '^[[:blank:]]*$' > default-compilers2
-        grep -Fvxf default-compilers compilers > versioned-compilers
-        cat versioned-compilers | xargs -I§ bash -c 'realpath "$(command -v §)" 2>/dev/null' | paste - versioned-compilers | grep -Ev '^[[:blank:]]*$' > versioned-compilers2
-        sed 's/-[1-9][0-9\.]*$//' versioned-compilers2 | grep -Fxvf- default-compilers2 > compilers2
-        cat versioned-compilers2 >> compilers2
-        cut -f2 compilers2 > compilers
-        rm -f compilers2 default-compilers2 versioned-compilers2
-        cat compilers
-        scripts/warnings-summary.sh $(< compilers)
+        scripts/warnings-summary.sh
+        . scripts/lib.sh
+        get_compilers
+        printf '%s\n' "${compilers[@]}" > compilers
 
     - name: GCC debug builds
       run: |
@@ -107,28 +100,35 @@ jobs:
     - name: Report
       run: |
         set +e
-        ng=$(shopt -p nullglob)
         shopt -s nullglob
         a=($(printf '%s\n' build/*/failed | grep -Ev '^[[:blank:]]*$' | sort -V -r))
-        $ng
-        if (( ${#a[@]} )); then
+        b=($(printf '%s\n' build/*/test   | grep -Ev '^[[:blank:]]*$' | sort -V -r))
+        c=($(printf '%s\n' build/*/       | grep -Ev '^[[:blank:]]*$' | sort -V -r))
+        declare -i m=${#a[@]} n=0 p=${#b[@]} q=${#c[@]}
+        x="$m/$q build failure"
+        (( m == 1 )) || x+='s'
+        (( m == 0 )) || x+=':'
+        echo "$x"
+        if (( m )); then
           a=("${a[@]%/failed}")
-          printf '%s\n' "Failures: ${#a[@]}" "${a[@]/#build\//- }"
-          exit 1
+          printf '%s\n' "${a[@]/#build\//- }"
         fi
-        echo 'All builds succeeded, running tests...'
-        declare -i n=0
-        for x in $(printf '%s\n' build/*/test | grep -Ev '^[[:blank:]]*$' | sort -V -r); do
-          y=$("$x" 2>&1)
-          (( n += $? != 0 ))
-          x="${x#build/}"
-          printf -vx -- '%-13s|' "${x%/test}"
-          echo "$y" | sed "s,^,$x ,"
-        done
-        if (( n )); then
-          echo "Failures: $n"
-          exit 1
+        if (( p )); then
+          echo 'Running tests...'
+          for x in "${b[@]}"; do
+            y=$("$x" 2>&1)
+            (( n += $? != 0 ))
+            x="${x#build/}"
+            printf -vx -- '%-13s|' "${x%/test}"
+            echo "$y" | sed "s,^,$x ,"
+          done
+          x="$n/$p test failure"
+          (( n == 1 )) || x+='s'
+          echo "$x"
         fi
+        ((p = q - m - n))
+        echo "$p/$q in the green"
+        (( p == q ))
 
   build-macos-14:
     runs-on: macos-14
@@ -140,9 +140,14 @@ jobs:
         echo "bash $BASH_VERSION"
         brew update
         brew upgrade
-        brew install bash binutils cjson coreutils gnu-sed llvm make pkg-config
-        p="$(brew --prefix)"
-        PATH="$p/opt/binutils/bin:$p/opt/llvm/bin:$p/opt/coreutils/libexec/gnubin:$p/opt/gnu-sed/libexec/gnubin:$p/opt/make/libexec/gnubin:$PATH"
+        brew install bash binutils cjson coreutils gnu-sed llvm make
+        if [[ -z "$HOMEBREW_PREFIX" ]]; then
+          export HOMEBREW_PREFIX="$(brew --prefix)"
+          echo 'export HOMEBREW_PREFIX="$(brew --prefix)"' >> "$HOME/.bash_profile"
+          echo "HOMEBREW_PREFIX=$HOMEBREW_PREFIX" >> "$GITHUB_ENV"
+        fi
+        export PATH="$HOMEBREW_PREFIX/opt/binutils/bin:$HOMEBREW_PREFIX/opt/llvm/bin:$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$PATH"
+        echo "export PATH=\"$PATH\"" >> "$HOME/.bash_profile"
         echo "PATH=$PATH" >> "$GITHUB_ENV"
 
     - uses: actions/checkout@v4
@@ -154,17 +159,10 @@ jobs:
         uname -a
         echo "bash $BASH_VERSION"
         alias nproc='sysctl -n hw.logicalcpu'
-        { compgen -c clang; compgen -c gcc; } | grep -E '^(clang|gcc)(-[1-9][0-9]*(\.[0-9]+)*)?$' | sort -V -u -r > compilers
-        grep -Fxe clang -e gcc compilers > default-compilers
-        cat default-compilers | xargs -I§ bash -c 'realpath "$(command -v §)" 2>/dev/null' | paste - default-compilers | grep -Ev '^[[:blank:]]*$' > default-compilers2
-        grep -Fvxf default-compilers compilers > versioned-compilers
-        cat versioned-compilers | xargs -I§ bash -c 'realpath "$(command -v §)" 2>/dev/null' | paste - versioned-compilers | grep -Ev '^[[:blank:]]*$' > versioned-compilers2
-        sed 's/-[1-9][0-9\.]*$//' versioned-compilers2 | grep -Fxvf- default-compilers2 > compilers2
-        cat versioned-compilers2 >> compilers2
-        cut -f2 compilers2 > compilers
-        rm -f compilers2 default-compilers2 versioned-compilers2
-        cat compilers
-        scripts/warnings-summary.sh $(< compilers)
+        scripts/warnings-summary.sh
+        . scripts/lib.sh
+        get_compilers
+        printf '%s\n' "${compilers[@]}" > compilers
 
     - name: GCC debug builds
       shell: bash
@@ -221,3 +219,36 @@ jobs:
           make -j$(nproc) -C src O="../$_dir" CC="$_cc" CXX="$_cxx"
           (( $? == 0 )) || touch "$_dir/failed"
         done
+
+    - name: Report
+      run: |
+        set +e
+        shopt -s nullglob
+        a=($(printf '%s\n' build/*/failed | grep -Ev '^[[:blank:]]*$' | sort -V -r))
+        b=($(printf '%s\n' build/*/test   | grep -Ev '^[[:blank:]]*$' | sort -V -r))
+        c=($(printf '%s\n' build/*/       | grep -Ev '^[[:blank:]]*$' | sort -V -r))
+        declare -i m=${#a[@]} n=0 p=${#b[@]} q=${#c[@]}
+        x="$m/$q build failure"
+        (( m == 1 )) || x+='s'
+        (( m == 0 )) || x+=':'
+        echo "$x"
+        if (( m )); then
+          a=("${a[@]%/failed}")
+          printf '%s\n' "${a[@]/#build\//- }"
+        fi
+        if (( p )); then
+          echo 'Running tests...'
+          for x in "${b[@]}"; do
+            y=$("$x" 2>&1)
+            (( n += $? != 0 ))
+            x="${x#build/}"
+            printf -vx -- '%-13s|' "${x%/test}"
+            echo "$y" | sed "s,^,$x ,"
+          done
+          x="$n/$p test failure"
+          (( n == 1 )) || x+='s'
+          echo "$x"
+        fi
+        ((p = q - m - n))
+        echo "$p/$q in the green"
+        (( p == q ))
